version: "2"
services:
  app:
    container_name: goweb1
    image: golang:1.13.1
    volumes:
      - ./src:/go/src
    working_dir: /go/src
    ports: 
      - "3030:3001"
    command: /bin/bash  -c "go run /go/src/main.go"
